export interface Salon {
  id: string;
  name: { en: string; ar: string };
  description: { en: string; ar: string };
  logo: string;
  cover: string;
  gallery: string[];
  rating: number;
  reviewsCount: number;
  location: { en: string; ar: string };
  neighborhood: string;
  phone: string;
  whatsapp: string;
  instagram: string;
  priceRange: '$$' | '$$$' | '$$$$';
  isLuxury: boolean;
  hasHomeService: boolean;
  services: Service[];
  staff: Staff[];
  workingHours: WorkingHours[];
  category: string;
  tags: string[];
  offers: string[];
}

export interface Service {
  id: string;
  name: { en: string; ar: string };
  price: number;
  duration: number;
  category: string;
}

export interface Staff {
  id: string;
  name: string;
  role: { en: string; ar: string };
  photo: string;
  rating: number;
  specialty: string;
}

export interface WorkingHours {
  day: string;
  open: string;
  close: string;
  isOpen: boolean;
}

export interface Offer {
  id: string;
  title: { en: string; ar: string };
  description: { en: string; ar: string };
  originalPrice: number;
  discountedPrice: number;
  discount: number;
  expiresAt: string;
  image: string;
  salonId: string;
  salonName: string;
}

export interface Category {
  id: string;
  name: { en: string; ar: string };
  icon: string;
  color: string;
  gradient: string;
  count: number;
}

export interface Review {
  id: string;
  customerName: string;
  customerAvatar: string;
  rating: number;
  comment: { en: string; ar: string };
  date: string;
  salonId: string;
  service: string;
}

export interface Package {
  id: string;
  name: { en: string; ar: string };
  description: { en: string; ar: string };
  services: string[];
  originalPrice: number;
  price: number;
  image: string;
  duration: number;
}

export interface BlogPost {
  id: string;
  title: { en: string; ar: string };
  excerpt: { en: string; ar: string };
  image: string;
  category: string;
  date: string;
  readTime: number;
}

const defaultWorkingHours: WorkingHours[] = [
  { day: 'Sunday', open: '09:00', close: '22:00', isOpen: true },
  { day: 'Monday', open: '09:00', close: '22:00', isOpen: true },
  { day: 'Tuesday', open: '09:00', close: '22:00', isOpen: true },
  { day: 'Wednesday', open: '09:00', close: '22:00', isOpen: true },
  { day: 'Thursday', open: '09:00', close: '22:00', isOpen: true },
  { day: 'Friday', open: '14:00', close: '22:00', isOpen: true },
  { day: 'Saturday', open: '09:00', close: '22:00', isOpen: true },
];

const hairServices: Service[] = [
  { id: 's1', name: { en: 'Haircut & Style', ar: 'قص وتسريح' }, price: 150, duration: 60, category: 'hair' },
  { id: 's2', name: { en: 'Balayage', ar: 'بالياج' }, price: 450, duration: 180, category: 'hair' },
  { id: 's3', name: { en: 'Keratin Treatment', ar: 'كيراتين' }, price: 600, duration: 240, category: 'hair' },
  { id: 's4', name: { en: 'Hair Color Full', ar: 'صبغة شاملة' }, price: 350, duration: 120, category: 'hair' },
  { id: 's5', name: { en: 'Blowout', ar: 'بروش' }, price: 100, duration: 45, category: 'hair' },
];

const nailServices: Service[] = [
  { id: 'n1', name: { en: 'Gel Manicure', ar: 'مناكير جل' }, price: 120, duration: 60, category: 'nails' },
  { id: 'n2', name: { en: 'French Pedicure', ar: 'باديكير فرنسي' }, price: 150, duration: 75, category: 'nails' },
  { id: 'n3', name: { en: 'Nail Art (per nail)', ar: 'نقش أظافر' }, price: 20, duration: 5, category: 'nails' },
  { id: 'n4', name: { en: 'Acrylic Full Set', ar: 'أكريليك كامل' }, price: 250, duration: 120, category: 'nails' },
];

const makeupServices: Service[] = [
  { id: 'm1', name: { en: 'Bridal Makeup', ar: 'مكياج عروس' }, price: 800, duration: 120, category: 'makeup' },
  { id: 'm2', name: { en: 'Evening Makeup', ar: 'مكياج سهرة' }, price: 300, duration: 60, category: 'makeup' },
  { id: 'm3', name: { en: 'Everyday Makeup', ar: 'مكياج يومي' }, price: 150, duration: 45, category: 'makeup' },
];

const staffPool: Staff[] = [
  { id: 'st1', name: 'Sara Al-Ahmad', role: { en: 'Senior Stylist', ar: 'مصففة شعر أولى' }, photo: 'https://picsum.photos/seed/staff1/200/200', rating: 4.9, specialty: 'Balayage & Color' },
  { id: 'st2', name: 'Nour Al-Rashid', role: { en: 'Nail Technician', ar: 'فنية أظافر' }, photo: 'https://picsum.photos/seed/staff2/200/200', rating: 4.8, specialty: 'Gel & Nail Art' },
  { id: 'st3', name: 'Hana Al-Qahtani', role: { en: 'Makeup Artist', ar: 'فنانة مكياج' }, photo: 'https://picsum.photos/seed/staff3/200/200', rating: 5.0, specialty: 'Bridal & Events' },
  { id: 'st4', name: 'Reem Al-Dosari', role: { en: 'Esthetician', ar: 'أخصائية تجميل' }, photo: 'https://picsum.photos/seed/staff4/200/200', rating: 4.7, specialty: 'Facials & Skincare' },
  { id: 'st5', name: 'Dina Al-Harbi', role: { en: 'Eyebrow Specialist', ar: 'أخصائية حواجب' }, photo: 'https://picsum.photos/seed/staff5/200/200', rating: 4.9, specialty: 'Threading & Tinting' },
  { id: 'st6', name: 'Maya Al-Zahrani', role: { en: 'Lash Technician', ar: 'فنية رموش' }, photo: 'https://picsum.photos/seed/staff6/200/200', rating: 4.8, specialty: 'Volume & Classic Lashes' },
];

export const salons: Salon[] = [
  {
    id: '1',
    name: { en: 'Lumière Beauty Lounge', ar: 'لوميير لاونج الجمال' },
    description: { en: 'Premium beauty destination in Al Olaya offering world-class hair, nail, and makeup services in a luxurious setting.', ar: 'وجهة تجميل فاخرة في العليا تقدم خدمات شعر وأظافر ومكياج عالمية المستوى.' },
    logo: 'https://picsum.photos/seed/logo1/200/200',
    cover: 'https://picsum.photos/seed/salon1cover/1200/600',
    gallery: ['https://picsum.photos/seed/s1g1/800/600', 'https://picsum.photos/seed/s1g2/800/600', 'https://picsum.photos/seed/s1g3/800/600', 'https://picsum.photos/seed/s1g4/800/600'],
    rating: 4.9,
    reviewsCount: 342,
    location: { en: 'Al Olaya District, Riyadh', ar: 'حي العليا، الرياض' },
    neighborhood: 'Al Olaya',
    phone: '+966-11-234-5678',
    whatsapp: '+966501234567',
    instagram: '@lumiere.riyadh',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [...hairServices, ...nailServices, ...makeupServices],
    staff: [staffPool[0], staffPool[1], staffPool[2]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['luxury', 'bridal', 'color specialist'],
    offers: ['offer1', 'offer2'],
  },
  {
    id: '2',
    name: { en: 'Nakheel Nail Studio', ar: 'نخيل ستوديو الأظافر' },
    description: { en: 'Riyadh\'s most-loved nail studio in Al Nakheel with over 200 gel colors and award-winning nail art.', ar: 'أكثر صالونات الأظافر المحبوبة في الرياض بحي النخيل.' },
    logo: 'https://picsum.photos/seed/logo2/200/200',
    cover: 'https://picsum.photos/seed/salon2cover/1200/600',
    gallery: ['https://picsum.photos/seed/s2g1/800/600', 'https://picsum.photos/seed/s2g2/800/600', 'https://picsum.photos/seed/s2g3/800/600'],
    rating: 4.8,
    reviewsCount: 289,
    location: { en: 'Al Nakheel District, Riyadh', ar: 'حي النخيل، الرياض' },
    neighborhood: 'Al Nakheel',
    phone: '+966-11-345-6789',
    whatsapp: '+966502345678',
    instagram: '@nakheel.nails',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...nailServices],
    staff: [staffPool[1], staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'nails',
    tags: ['nail art', 'gel', 'acrylic'],
    offers: ['offer3'],
  },
  {
    id: '3',
    name: { en: 'Malaz Bridal Studio', ar: 'ستوديو الملاز للعرائس' },
    description: { en: 'The ultimate bridal experience in Al Malaz. Full packages for the perfect wedding day look.', ar: 'تجربة العروس المثالية في حي الملاز. باقات كاملة ليوم زفاف مثالي.' },
    logo: 'https://picsum.photos/seed/logo3/200/200',
    cover: 'https://picsum.photos/seed/salon3cover/1200/600',
    gallery: ['https://picsum.photos/seed/s3g1/800/600', 'https://picsum.photos/seed/s3g2/800/600', 'https://picsum.photos/seed/s3g3/800/600'],
    rating: 4.9,
    reviewsCount: 198,
    location: { en: 'Al Malaz District, Riyadh', ar: 'حي الملاز، الرياض' },
    neighborhood: 'Al Malaz',
    phone: '+966-11-456-7890',
    whatsapp: '+966503456789',
    instagram: '@malaz.bridal',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [...makeupServices, ...hairServices],
    staff: [staffPool[2], staffPool[0]],
    workingHours: defaultWorkingHours,
    category: 'makeup',
    tags: ['bridal', 'luxury', 'events'],
    offers: ['offer4', 'offer5'],
  },
  {
    id: '4',
    name: { en: 'Rabwah Glow Skincare', ar: 'ربوة جلو للعناية بالبشرة' },
    description: { en: 'Advanced skincare treatments and facials in Al Rabwah using premium European products.', ar: 'علاجات بشرة متقدمة في حي الربوة باستخدام منتجات أوروبية فاخرة.' },
    logo: 'https://picsum.photos/seed/logo4/200/200',
    cover: 'https://picsum.photos/seed/salon4cover/1200/600',
    gallery: ['https://picsum.photos/seed/s4g1/800/600', 'https://picsum.photos/seed/s4g2/800/600'],
    rating: 4.7,
    reviewsCount: 156,
    location: { en: 'Al Rabwah District, Riyadh', ar: 'حي الربوة، الرياض' },
    neighborhood: 'Al Rabwah',
    phone: '+966-11-567-8901',
    whatsapp: '+966504567890',
    instagram: '@rabwah.glow',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [
      { id: 'sk1', name: { en: 'HydraFacial', ar: 'هيدرا فيشل' }, price: 450, duration: 60, category: 'skincare' },
      { id: 'sk2', name: { en: 'Chemical Peel', ar: 'تقشير كيميائي' }, price: 350, duration: 45, category: 'skincare' },
      { id: 'sk3', name: { en: 'LED Light Therapy', ar: 'علاج الضوء' }, price: 250, duration: 30, category: 'skincare' },
    ],
    staff: [staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'skincare',
    tags: ['skincare', 'facial', 'glow'],
    offers: ['offer6'],
  },
  {
    id: '5',
    name: { en: 'Sulaimaniyah Lash Bar', ar: 'سليمانية لاش بار' },
    description: { en: 'Riyadh\'s premier lash extension studio in Al Sulaimaniyah. Volume, mega volume, and classic sets.', ar: 'أول استوديو رموش متخصص في الرياض بحي السليمانية.' },
    logo: 'https://picsum.photos/seed/logo5/200/200',
    cover: 'https://picsum.photos/seed/salon5cover/1200/600',
    gallery: ['https://picsum.photos/seed/s5g1/800/600', 'https://picsum.photos/seed/s5g2/800/600'],
    rating: 4.8,
    reviewsCount: 231,
    location: { en: 'Al Sulaimaniyah, Riyadh', ar: 'حي السليمانية، الرياض' },
    neighborhood: 'Al Sulaimaniyah',
    phone: '+966-11-678-9012',
    whatsapp: '+966505678901',
    instagram: '@sulaimaniyah.lash',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: true,
    services: [
      { id: 'l1', name: { en: 'Classic Lash Set', ar: 'رموش كلاسيك' }, price: 300, duration: 90, category: 'lashes' },
      { id: 'l2', name: { en: 'Volume Lash Set', ar: 'رموش فولوم' }, price: 450, duration: 120, category: 'lashes' },
      { id: 'l3', name: { en: 'Lash Lift & Tint', ar: 'رفع وصبغ رموش' }, price: 200, duration: 60, category: 'lashes' },
    ],
    staff: [staffPool[5]],
    workingHours: defaultWorkingHours,
    category: 'lashes',
    tags: ['lashes', 'volume', 'extensions'],
    offers: ['offer7'],
  },
  {
    id: '6',
    name: { en: 'Worood Eyebrow Studio', ar: 'ورود ستوديو الحواجب' },
    description: { en: 'Eyebrow artistry at its finest. Microblading, threading, lamination in Al Wurud district.', ar: 'فن الحواجب على أعلى مستوى. مايكروبليدينج وخيط وترميم.' },
    logo: 'https://picsum.photos/seed/logo6/200/200',
    cover: 'https://picsum.photos/seed/salon6cover/1200/600',
    gallery: ['https://picsum.photos/seed/s6g1/800/600', 'https://picsum.photos/seed/s6g2/800/600'],
    rating: 4.9,
    reviewsCount: 178,
    location: { en: 'Al Wurud District, Riyadh', ar: 'حي الورود، الرياض' },
    neighborhood: 'Al Wurud',
    phone: '+966-11-789-0123',
    whatsapp: '+966506789012',
    instagram: '@worood.brows',
    priceRange: '$$',
    isLuxury: false,
    hasHomeService: false,
    services: [
      { id: 'e1', name: { en: 'Microblading', ar: 'مايكروبليدينج' }, price: 800, duration: 120, category: 'eyebrows' },
      { id: 'e2', name: { en: 'Eyebrow Lamination', ar: 'لاميناشن حواجب' }, price: 250, duration: 60, category: 'eyebrows' },
      { id: 'e3', name: { en: 'Threading & Tinting', ar: 'خيط وصبغ' }, price: 80, duration: 30, category: 'eyebrows' },
    ],
    staff: [staffPool[4]],
    workingHours: defaultWorkingHours,
    category: 'eyebrows',
    tags: ['eyebrows', 'microblading', 'lamination'],
    offers: ['offer8'],
  },
  {
    id: '7',
    name: { en: 'Serenity Spa & Massage', ar: 'سيرينيتي سبا ومساج' },
    description: { en: 'Luxury spa experience with traditional and modern massage therapies in Al Hamra.', ar: 'تجربة سبا فاخرة مع علاجات مساج تقليدية وحديثة في حي الحمراء.' },
    logo: 'https://picsum.photos/seed/logo7/200/200',
    cover: 'https://picsum.photos/seed/salon7cover/1200/600',
    gallery: ['https://picsum.photos/seed/s7g1/800/600', 'https://picsum.photos/seed/s7g2/800/600'],
    rating: 4.7,
    reviewsCount: 145,
    location: { en: 'Al Hamra District, Riyadh', ar: 'حي الحمراء، الرياض' },
    neighborhood: 'Al Hamra',
    phone: '+966-11-890-1234',
    whatsapp: '+966507890123',
    instagram: '@serenity.spa.riyadh',
    priceRange: '$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [
      { id: 'ms1', name: { en: 'Swedish Massage 60min', ar: 'مساج سويدي ٦٠ دقيقة' }, price: 350, duration: 60, category: 'massage' },
      { id: 'ms2', name: { en: 'Deep Tissue Massage', ar: 'مساج عميق' }, price: 450, duration: 90, category: 'massage' },
      { id: 'ms3', name: { en: 'Hot Stone Therapy', ar: 'علاج الحجارة الساخنة' }, price: 500, duration: 90, category: 'massage' },
      { id: 'ms4', name: { en: 'Moroccan Bath', ar: 'حمام مغربي' }, price: 400, duration: 120, category: 'massage' },
    ],
    staff: [staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'massage',
    tags: ['spa', 'massage', 'relaxation'],
    offers: ['offer9'],
  },
  {
    id: '8',
    name: { en: 'Gold Rose Beauty', ar: 'جولد روز بيوتي' },
    description: { en: 'Full-service luxury beauty salon in Al Muhammadiyah catering to all your beauty needs.', ar: 'صالون تجميل فاخر متكامل في حي المحمدية.' },
    logo: 'https://picsum.photos/seed/logo8/200/200',
    cover: 'https://picsum.photos/seed/salon8cover/1200/600',
    gallery: ['https://picsum.photos/seed/s8g1/800/600', 'https://picsum.photos/seed/s8g2/800/600'],
    rating: 4.6,
    reviewsCount: 267,
    location: { en: 'Al Muhammadiyah, Riyadh', ar: 'حي المحمدية، الرياض' },
    neighborhood: 'Al Muhammadiyah',
    phone: '+966-11-901-2345',
    whatsapp: '+966508901234',
    instagram: '@goldrose.beauty',
    priceRange: '$$$',
    isLuxury: true,
    hasHomeService: false,
    services: [...hairServices, ...makeupServices],
    staff: [staffPool[0], staffPool[2]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['luxury', 'full service', 'premium'],
    offers: ['offer10'],
  },
  {
    id: '9',
    name: { en: 'Yasmin Hair & Spa', ar: 'ياسمين هير وسبا' },
    description: { en: 'Boutique hair salon with signature treatments in Al Yasmin. Specializing in color and keratin.', ar: 'صالون شعر بوتيك مع علاجات مميزة في حي الياسمين.' },
    logo: 'https://picsum.photos/seed/logo9/200/200',
    cover: 'https://picsum.photos/seed/salon9cover/1200/600',
    gallery: ['https://picsum.photos/seed/s9g1/800/600', 'https://picsum.photos/seed/s9g2/800/600'],
    rating: 4.5,
    reviewsCount: 189,
    location: { en: 'Al Yasmin District, Riyadh', ar: 'حي الياسمين، الرياض' },
    neighborhood: 'Al Yasmin',
    phone: '+966-11-012-3456',
    whatsapp: '+966509012345',
    instagram: '@yasmin.hair',
    priceRange: '$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...hairServices],
    staff: [staffPool[0]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['color', 'keratin', 'haircut'],
    offers: [],
  },
  {
    id: '10',
    name: { en: 'Crystal Nails & Beauty', ar: 'كريستال نيلز وبيوتي' },
    description: { en: 'Trendy nail and beauty studio in Hittin with the latest techniques and designs.', ar: 'استوديو أظافر وتجميل عصري في حي حطين.' },
    logo: 'https://picsum.photos/seed/logo10/200/200',
    cover: 'https://picsum.photos/seed/salon10cover/1200/600',
    gallery: ['https://picsum.photos/seed/s10g1/800/600', 'https://picsum.photos/seed/s10g2/800/600'],
    rating: 4.7,
    reviewsCount: 312,
    location: { en: 'Hittin District, Riyadh', ar: 'حي حطين، الرياض' },
    neighborhood: 'Hittin',
    phone: '+966-11-123-4567',
    whatsapp: '+966510123456',
    instagram: '@crystal.nails.riyadh',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: true,
    services: [...nailServices],
    staff: [staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'nails',
    tags: ['nails', 'nail art', 'trendy'],
    offers: ['offer11'],
  },
  {
    id: '11',
    name: { en: 'Rosewood Makeup Studio', ar: 'روزوود ستوديو المكياج' },
    description: { en: 'Professional makeup studio in Al Rawdah for all occasions. Film, bridal, and editorial makeup.', ar: 'ستوديو مكياج احترافي في حي الروضة لجميع المناسبات.' },
    logo: 'https://picsum.photos/seed/logo11/200/200',
    cover: 'https://picsum.photos/seed/salon11cover/1200/600',
    gallery: ['https://picsum.photos/seed/s11g1/800/600'],
    rating: 4.8,
    reviewsCount: 134,
    location: { en: 'Al Rawdah, Riyadh', ar: 'حي الروضة، الرياض' },
    neighborhood: 'Al Rawdah',
    phone: '+966-11-234-5670',
    whatsapp: '+966511234567',
    instagram: '@rosewood.makeup',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: true,
    services: [...makeupServices],
    staff: [staffPool[2]],
    workingHours: defaultWorkingHours,
    category: 'makeup',
    tags: ['makeup', 'bridal', 'events'],
    offers: ['offer12'],
  },
  {
    id: '12',
    name: { en: 'Platinum Beauty Lounge', ar: 'بلاتينيوم بيوتي لاونج' },
    description: { en: 'Ultra-luxury beauty destination in Al Nakheel. Private suites and VIP packages available.', ar: 'وجهة تجميل فائقة الفخامة في حي النخيل. أجنحة خاصة وباقات VIP.' },
    logo: 'https://picsum.photos/seed/logo12/200/200',
    cover: 'https://picsum.photos/seed/salon12cover/1200/600',
    gallery: ['https://picsum.photos/seed/s12g1/800/600', 'https://picsum.photos/seed/s12g2/800/600', 'https://picsum.photos/seed/s12g3/800/600'],
    rating: 5.0,
    reviewsCount: 87,
    location: { en: 'Al Nakheel District, Riyadh', ar: 'حي النخيل، الرياض' },
    neighborhood: 'Al Nakheel',
    phone: '+966-11-345-6780',
    whatsapp: '+966512345678',
    instagram: '@platinum.lounge',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [...hairServices, ...nailServices, ...makeupServices],
    staff: [staffPool[0], staffPool[1], staffPool[2], staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['luxury', 'VIP', 'private suite'],
    offers: ['offer13', 'offer14'],
  },
  {
    id: '13',
    name: { en: 'Shimmer & Shine Salon', ar: 'شيمر وشاين صالون' },
    description: { en: 'Affordable beauty services without compromising quality in Al Marwah.', ar: 'خدمات تجميل بأسعار معقولة دون المساومة على الجودة في حي المروة.' },
    logo: 'https://picsum.photos/seed/logo13/200/200',
    cover: 'https://picsum.photos/seed/salon13cover/1200/600',
    gallery: ['https://picsum.photos/seed/s13g1/800/600'],
    rating: 4.4,
    reviewsCount: 423,
    location: { en: 'Al Marwah, Riyadh', ar: 'حي المروة، الرياض' },
    neighborhood: 'Al Marwah',
    phone: '+966-11-456-7891',
    whatsapp: '+966513456789',
    instagram: '@shimmershine.sa',
    priceRange: '$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...hairServices, ...nailServices],
    staff: [staffPool[0], staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['affordable', 'quality', 'full service'],
    offers: [],
  },
  {
    id: '14',
    name: { en: 'La Belle Coiffure', ar: 'لا بيل كوافور' },
    description: { en: 'French-inspired hair salon in Al Olaya. Expert colorists and stylists trained in Paris.', ar: 'صالون شعر بإلهام فرنسي في العليا. خبراء صبغ وتصفيف تدربوا في باريس.' },
    logo: 'https://picsum.photos/seed/logo14/200/200',
    cover: 'https://picsum.photos/seed/salon14cover/1200/600',
    gallery: ['https://picsum.photos/seed/s14g1/800/600', 'https://picsum.photos/seed/s14g2/800/600'],
    rating: 4.8,
    reviewsCount: 276,
    location: { en: 'Al Olaya District, Riyadh', ar: 'حي العليا، الرياض' },
    neighborhood: 'Al Olaya',
    phone: '+966-11-567-8902',
    whatsapp: '+966514567890',
    instagram: '@labelle.coiffure',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: false,
    services: [...hairServices],
    staff: [staffPool[0]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['French style', 'color', 'balayage'],
    offers: ['offer15'],
  },
  {
    id: '15',
    name: { en: 'Dazzle Nail Lounge', ar: 'دازل نيل لاونج' },
    description: { en: 'Trendy nail lounge in Al Malqa offering 300+ colors, nail art and spa pedicures.', ar: 'لاونج أظافر عصري في حي الملقا مع أكثر من ٣٠٠ لون.' },
    logo: 'https://picsum.photos/seed/logo15/200/200',
    cover: 'https://picsum.photos/seed/salon15cover/1200/600',
    gallery: ['https://picsum.photos/seed/s15g1/800/600'],
    rating: 4.6,
    reviewsCount: 198,
    location: { en: 'Al Malqa, Riyadh', ar: 'حي الملقا، الرياض' },
    neighborhood: 'Al Malqa',
    phone: '+966-11-678-9013',
    whatsapp: '+966515678901',
    instagram: '@dazzle.nails',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...nailServices],
    staff: [staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'nails',
    tags: ['nails', 'trendy', 'colors'],
    offers: [],
  },
  {
    id: '16',
    name: { en: 'Glow Up Beauty Bar', ar: 'جلو أب بيوتي بار' },
    description: { en: 'One-stop beauty bar in Hittin for quick, professional services. Walk-ins welcome.', ar: 'بار تجميل متكامل في حطين للخدمات السريعة والاحترافية.' },
    logo: 'https://picsum.photos/seed/logo16/200/200',
    cover: 'https://picsum.photos/seed/salon16cover/1200/600',
    gallery: ['https://picsum.photos/seed/s16g1/800/600'],
    rating: 4.5,
    reviewsCount: 334,
    location: { en: 'Hittin District, Riyadh', ar: 'حي حطين، الرياض' },
    neighborhood: 'Hittin',
    phone: '+966-11-789-0124',
    whatsapp: '+966516789012',
    instagram: '@glowup.bar',
    priceRange: '$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...makeupServices, ...nailServices],
    staff: [staffPool[2], staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'makeup',
    tags: ['quick service', 'walk-in', 'affordable'],
    offers: ['offer16'],
  },
  {
    id: '17',
    name: { en: 'Oasis Spa & Wellness', ar: 'أوازيس سبا وويلنس' },
    description: { en: 'Holistic wellness and beauty center in Al Sulimaniyah. Yoga, massage, and skincare under one roof.', ar: 'مركز صحة وجمال شامل في السليمانية. يوغا ومساج وعناية بالبشرة.' },
    logo: 'https://picsum.photos/seed/logo17/200/200',
    cover: 'https://picsum.photos/seed/salon17cover/1200/600',
    gallery: ['https://picsum.photos/seed/s17g1/800/600', 'https://picsum.photos/seed/s17g2/800/600'],
    rating: 4.7,
    reviewsCount: 167,
    location: { en: 'Al Sulaimaniyah, Riyadh', ar: 'حي السليمانية، الرياض' },
    neighborhood: 'Al Sulaimaniyah',
    phone: '+966-11-890-1235',
    whatsapp: '+966517890123',
    instagram: '@oasis.spa.riyadh',
    priceRange: '$$$',
    isLuxury: true,
    hasHomeService: false,
    services: [
      { id: 'ms5', name: { en: 'Aromatherapy Massage', ar: 'مساج بالعطور' }, price: 400, duration: 75, category: 'massage' },
      { id: 'ms6', name: { en: 'Body Scrub', ar: 'سكراب جسم' }, price: 300, duration: 60, category: 'massage' },
    ],
    staff: [staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'massage',
    tags: ['wellness', 'spa', 'holistic'],
    offers: ['offer17'],
  },
  {
    id: '18',
    name: { en: 'Velvet Touch Beauty', ar: 'فيلفيت تاتش بيوتي' },
    description: { en: 'Premium beauty services with a personal touch in Al Nakheel. Specialized in bridal packages.', ar: 'خدمات تجميل متميزة باللمسة الشخصية في النخيل.' },
    logo: 'https://picsum.photos/seed/logo18/200/200',
    cover: 'https://picsum.photos/seed/salon18cover/1200/600',
    gallery: ['https://picsum.photos/seed/s18g1/800/600'],
    rating: 4.8,
    reviewsCount: 145,
    location: { en: 'Al Nakheel, Riyadh', ar: 'حي النخيل، الرياض' },
    neighborhood: 'Al Nakheel',
    phone: '+966-11-901-2346',
    whatsapp: '+966518901234',
    instagram: '@velvet.beauty.sa',
    priceRange: '$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [...makeupServices, ...hairServices],
    staff: [staffPool[2], staffPool[0]],
    workingHours: defaultWorkingHours,
    category: 'makeup',
    tags: ['bridal', 'events', 'premium'],
    offers: ['offer18'],
  },
  {
    id: '19',
    name: { en: 'Bloom Lashes Studio', ar: 'بلوم لاشيس ستوديو' },
    description: { en: 'Specialized lash and brow studio in Al Malaz with master technicians.', ar: 'ستوديو متخصص في الرموش والحواجب في الملاز.' },
    logo: 'https://picsum.photos/seed/logo19/200/200',
    cover: 'https://picsum.photos/seed/salon19cover/1200/600',
    gallery: ['https://picsum.photos/seed/s19g1/800/600'],
    rating: 4.9,
    reviewsCount: 201,
    location: { en: 'Al Malaz, Riyadh', ar: 'حي الملاز، الرياض' },
    neighborhood: 'Al Malaz',
    phone: '+966-11-012-3457',
    whatsapp: '+966519012345',
    instagram: '@bloom.lashes',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [
      { id: 'l4', name: { en: 'Hybrid Lash Set', ar: 'رموش هايبرد' }, price: 380, duration: 100, category: 'lashes' },
      { id: 'e4', name: { en: 'Brow Microshading', ar: 'مايكروشيدنج حواجب' }, price: 700, duration: 90, category: 'eyebrows' },
    ],
    staff: [staffPool[5], staffPool[4]],
    workingHours: defaultWorkingHours,
    category: 'lashes',
    tags: ['lashes', 'brows', 'specialist'],
    offers: [],
  },
  {
    id: '20',
    name: { en: 'Radiance Skin Clinic', ar: 'راديانس عيادة البشرة' },
    description: { en: 'Medical-grade skincare treatments in Al Wurud. Laser, Botox, fillers and more.', ar: 'علاجات بشرة بمستوى طبي في الورود. ليزر وبوتوكس وفيلر.' },
    logo: 'https://picsum.photos/seed/logo20/200/200',
    cover: 'https://picsum.photos/seed/salon20cover/1200/600',
    gallery: ['https://picsum.photos/seed/s20g1/800/600'],
    rating: 4.7,
    reviewsCount: 89,
    location: { en: 'Al Wurud, Riyadh', ar: 'حي الورود، الرياض' },
    neighborhood: 'Al Wurud',
    phone: '+966-11-123-4568',
    whatsapp: '+966520123456',
    instagram: '@radiance.skin',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: false,
    services: [
      { id: 'sk4', name: { en: 'Laser Hair Removal', ar: 'إزالة الشعر بالليزر' }, price: 600, duration: 60, category: 'skincare' },
      { id: 'sk5', name: { en: 'Botox Treatment', ar: 'علاج البوتوكس' }, price: 1500, duration: 45, category: 'skincare' },
    ],
    staff: [staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'skincare',
    tags: ['medical', 'laser', 'anti-aging'],
    offers: ['offer19'],
  },
  {
    id: '21',
    name: { en: 'Pearl Beauty Center', ar: 'مركز بيرل للجمال' },
    description: { en: 'Comprehensive beauty center in Al Rabwah. Hair, nails, skincare all in one place.', ar: 'مركز تجميل شامل في الربوة.' },
    logo: 'https://picsum.photos/seed/logo21/200/200',
    cover: 'https://picsum.photos/seed/salon21cover/1200/600',
    gallery: ['https://picsum.photos/seed/s21g1/800/600'],
    rating: 4.5,
    reviewsCount: 256,
    location: { en: 'Al Rabwah, Riyadh', ar: 'حي الربوة، الرياض' },
    neighborhood: 'Al Rabwah',
    phone: '+966-11-234-5679',
    whatsapp: '+966521234567',
    instagram: '@pearl.beauty.sa',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...hairServices, ...nailServices],
    staff: [staffPool[0], staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['comprehensive', 'full service'],
    offers: [],
  },
  {
    id: '22',
    name: { en: 'The Glam Room', ar: 'ذا جلام روم' },
    description: { en: 'Social media-worthy beauty studio in Al Malqa. Perfect for content creators.', ar: 'استوديو تجميل مثالي لمواقع التواصل الاجتماعي في الملقا.' },
    logo: 'https://picsum.photos/seed/logo22/200/200',
    cover: 'https://picsum.photos/seed/salon22cover/1200/600',
    gallery: ['https://picsum.photos/seed/s22g1/800/600', 'https://picsum.photos/seed/s22g2/800/600'],
    rating: 4.8,
    reviewsCount: 445,
    location: { en: 'Al Malqa, Riyadh', ar: 'حي الملقا، الرياض' },
    neighborhood: 'Al Malqa',
    phone: '+966-11-345-6781',
    whatsapp: '+966522345678',
    instagram: '@theglam.room',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...makeupServices, ...hairServices],
    staff: [staffPool[2], staffPool[0]],
    workingHours: defaultWorkingHours,
    category: 'makeup',
    tags: ['Instagram', 'content creator', 'trendy'],
    offers: ['offer20'],
  },
  {
    id: '23',
    name: { en: 'Aura Wellness Spa', ar: 'أورا ويلنس سبا' },
    description: { en: 'Luxury spa retreat in Al Hamra offering signature treatments.', ar: 'ملاذ سبا فاخر في الحمراء يقدم علاجات مميزة.' },
    logo: 'https://picsum.photos/seed/logo23/200/200',
    cover: 'https://picsum.photos/seed/salon23cover/1200/600',
    gallery: ['https://picsum.photos/seed/s23g1/800/600'],
    rating: 4.6,
    reviewsCount: 123,
    location: { en: 'Al Hamra, Riyadh', ar: 'حي الحمراء، الرياض' },
    neighborhood: 'Al Hamra',
    phone: '+966-11-456-7892',
    whatsapp: '+966523456789',
    instagram: '@aura.spa.riyadh',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [
      { id: 'ms7', name: { en: 'Signature Aura Massage', ar: 'مساج الأورا المميز' }, price: 650, duration: 120, category: 'massage' },
    ],
    staff: [staffPool[3]],
    workingHours: defaultWorkingHours,
    category: 'massage',
    tags: ['luxury', 'spa', 'wellness'],
    offers: [],
  },
  {
    id: '24',
    name: { en: 'Chic Nails & Spa', ar: 'شيك نيلز وسبا' },
    description: { en: 'Upscale nail spa in Al Muhammadiyah with Korean-inspired nail techniques.', ar: 'صالون أظافر راقٍ في المحمدية بتقنيات كورية.' },
    logo: 'https://picsum.photos/seed/logo24/200/200',
    cover: 'https://picsum.photos/seed/salon24cover/1200/600',
    gallery: ['https://picsum.photos/seed/s24g1/800/600'],
    rating: 4.7,
    reviewsCount: 178,
    location: { en: 'Al Muhammadiyah, Riyadh', ar: 'حي المحمدية، الرياض' },
    neighborhood: 'Al Muhammadiyah',
    phone: '+966-11-567-8903',
    whatsapp: '+966524567890',
    instagram: '@chic.nails.sa',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...nailServices],
    staff: [staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'nails',
    tags: ['Korean style', 'nail art', 'spa'],
    offers: [],
  },
  {
    id: '25',
    name: { en: 'Bliss Beauty Studio', ar: 'بليس بيوتي ستوديو' },
    description: { en: 'Modern beauty studio in Al Rawdah specializing in natural looks and organic products.', ar: 'ستوديو تجميل عصري في الروضة متخصص في الإطلالات الطبيعية.' },
    logo: 'https://picsum.photos/seed/logo25/200/200',
    cover: 'https://picsum.photos/seed/salon25cover/1200/600',
    gallery: ['https://picsum.photos/seed/s25g1/800/600'],
    rating: 4.5,
    reviewsCount: 234,
    location: { en: 'Al Rawdah, Riyadh', ar: 'حي الروضة، الرياض' },
    neighborhood: 'Al Rawdah',
    phone: '+966-11-678-9014',
    whatsapp: '+966525678901',
    instagram: '@bliss.beauty.riyadh',
    priceRange: '$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...hairServices, ...makeupServices],
    staff: [staffPool[0], staffPool[2]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['organic', 'natural', 'eco-friendly'],
    offers: [],
  },
  {
    id: '26',
    name: { en: 'Diamond Lash & Brow', ar: 'دايموند لاش وبراو' },
    description: { en: 'Expert lash and brow studio in Al Worood with nano-brow and mega volume techniques.', ar: 'استوديو متخصص في الرموش والحواجب في الورود.' },
    logo: 'https://picsum.photos/seed/logo26/200/200',
    cover: 'https://picsum.photos/seed/salon26cover/1200/600',
    gallery: ['https://picsum.photos/seed/s26g1/800/600'],
    rating: 4.9,
    reviewsCount: 167,
    location: { en: 'Al Wurud, Riyadh', ar: 'حي الورود، الرياض' },
    neighborhood: 'Al Wurud',
    phone: '+966-11-789-0125',
    whatsapp: '+966526789012',
    instagram: '@diamond.lash',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [
      { id: 'l5', name: { en: 'Mega Volume Lashes', ar: 'رموش ميجا فولوم' }, price: 550, duration: 150, category: 'lashes' },
      { id: 'e5', name: { en: 'Nano Brows', ar: 'نانو براوز' }, price: 900, duration: 120, category: 'eyebrows' },
    ],
    staff: [staffPool[5], staffPool[4]],
    workingHours: defaultWorkingHours,
    category: 'lashes',
    tags: ['lashes', 'nano brows', 'specialist'],
    offers: [],
  },
  {
    id: '27',
    name: { en: 'Maison de Beauté', ar: 'ميزون دو بوتيه' },
    description: { en: 'French-Arabic luxury beauty maison in Al Nakheel. Combining European techniques with Middle Eastern elegance.', ar: 'دار جمال فرنسية عربية فاخرة في النخيل.' },
    logo: 'https://picsum.photos/seed/logo27/200/200',
    cover: 'https://picsum.photos/seed/salon27cover/1200/600',
    gallery: ['https://picsum.photos/seed/s27g1/800/600', 'https://picsum.photos/seed/s27g2/800/600'],
    rating: 4.9,
    reviewsCount: 98,
    location: { en: 'Al Nakheel, Riyadh', ar: 'حي النخيل، الرياض' },
    neighborhood: 'Al Nakheel',
    phone: '+966-11-890-1236',
    whatsapp: '+966527890123',
    instagram: '@maison.beaute.sa',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [...hairServices, ...makeupServices, ...nailServices],
    staff: [staffPool[0], staffPool[2], staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['French', 'luxury', 'full service'],
    offers: [],
  },
  {
    id: '28',
    name: { en: 'Sakura Beauty Japan', ar: 'ساكورا بيوتي جابان' },
    description: { en: 'Japanese beauty techniques in Al Yasmin. Featuring J-beauty skincare and nail art.', ar: 'تقنيات جمال يابانية في الياسمين.' },
    logo: 'https://picsum.photos/seed/logo28/200/200',
    cover: 'https://picsum.photos/seed/salon28cover/1200/600',
    gallery: ['https://picsum.photos/seed/s28g1/800/600'],
    rating: 4.6,
    reviewsCount: 145,
    location: { en: 'Al Yasmin, Riyadh', ar: 'حي الياسمين، الرياض' },
    neighborhood: 'Al Yasmin',
    phone: '+966-11-901-2347',
    whatsapp: '+966528901234',
    instagram: '@sakura.beauty.sa',
    priceRange: '$$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...nailServices],
    staff: [staffPool[1]],
    workingHours: defaultWorkingHours,
    category: 'nails',
    tags: ['Japanese', 'J-beauty', 'nail art'],
    offers: [],
  },
  {
    id: '29',
    name: { en: 'Crown Beauty Palace', ar: 'قصر كراون للجمال' },
    description: { en: 'Royal treatment awaits at Crown Beauty Palace in Al Olaya. Ultimate luxury beauty experience.', ar: 'علاج ملكي في قصر كراون للجمال في العليا.' },
    logo: 'https://picsum.photos/seed/logo29/200/200',
    cover: 'https://picsum.photos/seed/salon29cover/1200/600',
    gallery: ['https://picsum.photos/seed/s29g1/800/600', 'https://picsum.photos/seed/s29g2/800/600'],
    rating: 5.0,
    reviewsCount: 67,
    location: { en: 'Al Olaya, Riyadh', ar: 'حي العليا، الرياض' },
    neighborhood: 'Al Olaya',
    phone: '+966-11-012-3458',
    whatsapp: '+966529012345',
    instagram: '@crown.beauty.palace',
    priceRange: '$$$$',
    isLuxury: true,
    hasHomeService: true,
    services: [...hairServices, ...nailServices, ...makeupServices],
    staff: [staffPool[0], staffPool[1], staffPool[2], staffPool[3], staffPool[4], staffPool[5]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['palace', 'VIP', 'royal', 'luxury'],
    offers: [],
  },
  {
    id: '30',
    name: { en: 'Studio 99 Beauty', ar: 'ستوديو ٩٩ بيوتي' },
    description: { en: 'Creative beauty studio in Hittin known for bold looks and experimental styles.', ar: 'استوديو تجميل إبداعي في حطين.' },
    logo: 'https://picsum.photos/seed/logo30/200/200',
    cover: 'https://picsum.photos/seed/salon30cover/1200/600',
    gallery: ['https://picsum.photos/seed/s30g1/800/600'],
    rating: 4.5,
    reviewsCount: 312,
    location: { en: 'Hittin, Riyadh', ar: 'حي حطين، الرياض' },
    neighborhood: 'Hittin',
    phone: '+966-11-123-4569',
    whatsapp: '+966530123456',
    instagram: '@studio99.sa',
    priceRange: '$$',
    isLuxury: false,
    hasHomeService: false,
    services: [...hairServices, ...makeupServices],
    staff: [staffPool[0], staffPool[2]],
    workingHours: defaultWorkingHours,
    category: 'hair',
    tags: ['creative', 'bold', 'experimental'],
    offers: [],
  },
];

export const categories: Category[] = [
  { id: 'hair', name: { en: 'Hair', ar: 'الشعر' }, icon: 'scissors', color: '#D4A853', gradient: 'from-amber-500 to-yellow-600', count: 145 },
  { id: 'nails', name: { en: 'Nails', ar: 'الأظافر' }, icon: 'sparkles', color: '#E91E8C', gradient: 'from-pink-500 to-rose-600', count: 98 },
  { id: 'makeup', name: { en: 'Makeup', ar: 'المكياج' }, icon: 'palette', color: '#9B59B6', gradient: 'from-purple-500 to-violet-600', count: 76 },
  { id: 'skincare', name: { en: 'Skincare', ar: 'العناية بالبشرة' }, icon: 'heart', color: '#2ECC71', gradient: 'from-emerald-500 to-green-600', count: 54 },
  { id: 'eyebrows', name: { en: 'Eyebrows', ar: 'الحواجب' }, icon: 'eye', color: '#3498DB', gradient: 'from-blue-500 to-cyan-600', count: 67 },
  { id: 'lashes', name: { en: 'Lashes', ar: 'الرموش' }, icon: 'star', color: '#E74C3C', gradient: 'from-red-500 to-orange-600', count: 43 },
  { id: 'massage', name: { en: 'Massage', ar: 'المساج' }, icon: 'zap', color: '#1ABC9C', gradient: 'from-teal-500 to-cyan-600', count: 32 },
  { id: 'bridal', name: { en: 'Bridal', ar: 'العرائس' }, icon: 'crown', color: '#F39C12', gradient: 'from-yellow-500 to-amber-600', count: 28 },
];

export const offers: Offer[] = [
  {
    id: 'offer1',
    title: { en: '50% Off Balayage', ar: '٥٠٪ خصم على البالياج' },
    description: { en: 'Get stunning balayage at half price. Limited slots available.', ar: 'احصلي على بالياج رائع بنصف السعر.' },
    originalPrice: 450,
    discountedPrice: 225,
    discount: 50,
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer1/600/400',
    salonId: '1',
    salonName: 'Lumière Beauty Lounge',
  },
  {
    id: 'offer2',
    title: { en: 'Bridal Package 30% Off', ar: '٣٠٪ خصم على باقة العروس' },
    description: { en: 'Complete bridal hair and makeup package at a special price.', ar: 'باقة شعر ومكياج كاملة للعروس بسعر خاص.' },
    originalPrice: 1500,
    discountedPrice: 1050,
    discount: 30,
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer2/600/400',
    salonId: '1',
    salonName: 'Lumière Beauty Lounge',
  },
  {
    id: 'offer3',
    title: { en: 'Manicure + Pedicure Deal', ar: 'عرض مناكير وباديكير' },
    description: { en: 'Get both mani and pedi for the price of one.', ar: 'احصلي على المناكير والباديكير بسعر واحد.' },
    originalPrice: 270,
    discountedPrice: 150,
    discount: 44,
    expiresAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer3/600/400',
    salonId: '2',
    salonName: 'Nakheel Nail Studio',
  },
  {
    id: 'offer4',
    title: { en: 'Keratin Treatment Special', ar: 'عرض علاج الكيراتين' },
    description: { en: 'Smooth, frizz-free hair for 6 months at a special price.', ar: 'شعر ناعم خالٍ من التجعد لمدة ٦ أشهر.' },
    originalPrice: 600,
    discountedPrice: 399,
    discount: 33,
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer4/600/400',
    salonId: '3',
    salonName: 'Malaz Bridal Studio',
  },
  {
    id: 'offer5',
    title: { en: 'HydraFacial Flash Sale', ar: 'تخفيض هيدرا فيشل' },
    description: { en: 'Book your HydraFacial today and save big!', ar: 'احجزي هيدرا فيشل اليوم ووفري كثيراً!' },
    originalPrice: 450,
    discountedPrice: 279,
    discount: 38,
    expiresAt: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer5/600/400',
    salonId: '4',
    salonName: 'Rabwah Glow Skincare',
  },
  {
    id: 'offer6',
    title: { en: 'Volume Lashes 25% Off', ar: '٢٥٪ خصم على رموش الفولوم' },
    description: { en: 'Gorgeous volume lash set at a special introductory price.', ar: 'رموش فولوم جميلة بسعر تعريفي خاص.' },
    originalPrice: 450,
    discountedPrice: 338,
    discount: 25,
    expiresAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer6/600/400',
    salonId: '5',
    salonName: 'Sulaimaniyah Lash Bar',
  },
  {
    id: 'offer7',
    title: { en: 'Microblading + Tint Combo', ar: 'كومبو مايكروبليدينج وصبغ' },
    description: { en: 'Perfect brows for 18 months with our microblading + tint combo.', ar: 'حواجب مثالية لمدة ١٨ شهراً مع كومبو المايكروبليدينج والصبغ.' },
    originalPrice: 880,
    discountedPrice: 680,
    discount: 23,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer7/600/400',
    salonId: '6',
    salonName: 'Worood Eyebrow Studio',
  },
  {
    id: 'offer8',
    title: { en: 'Spa Day Package', ar: 'باقة يوم السبا' },
    description: { en: 'Full spa day including massage, body scrub, and facial.', ar: 'يوم سبا كامل يشمل المساج والسكراب والفيشل.' },
    originalPrice: 1200,
    discountedPrice: 799,
    discount: 33,
    expiresAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer8/600/400',
    salonId: '7',
    salonName: 'Serenity Spa & Massage',
  },
  {
    id: 'offer9',
    title: { en: 'Full Color + Blowout', ar: 'صبغة كاملة وبروش' },
    description: { en: 'Complete hair color with a professional blowout finish.', ar: 'صبغة شعر كاملة مع بروش احترافي.' },
    originalPrice: 450,
    discountedPrice: 299,
    discount: 34,
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer9/600/400',
    salonId: '8',
    salonName: 'Gold Rose Beauty',
  },
  {
    id: 'offer10',
    title: { en: 'Acrylic Full Set Deal', ar: 'عرض أكريليك كامل' },
    description: { en: 'Gorgeous acrylic nails with your choice of color.', ar: 'أظافر أكريليك جميلة باختيارك للون.' },
    originalPrice: 250,
    discountedPrice: 175,
    discount: 30,
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer10/600/400',
    salonId: '10',
    salonName: 'Crystal Nails & Beauty',
  },
  {
    id: 'offer11',
    title: { en: 'Evening Makeup Special', ar: 'عرض مكياج السهرة' },
    description: { en: 'Look stunning for your evening event with our special makeup package.', ar: 'ابدي رائعة في حفلتك مع باقة مكياج السهرة.' },
    originalPrice: 300,
    discountedPrice: 199,
    discount: 34,
    expiresAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer11/600/400',
    salonId: '11',
    salonName: 'Rosewood Makeup Studio',
  },
  {
    id: 'offer12',
    title: { en: 'VIP Beauty Day', ar: 'يوم الجمال VIP' },
    description: { en: 'The ultimate VIP beauty experience at Platinum Beauty Lounge.', ar: 'تجربة الجمال المثلى VIP في بلاتينيوم بيوتي لاونج.' },
    originalPrice: 3000,
    discountedPrice: 1999,
    discount: 33,
    expiresAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer12/600/400',
    salonId: '12',
    salonName: 'Platinum Beauty Lounge',
  },
  {
    id: 'offer13',
    title: { en: 'Balayage Flash Deal', ar: 'عرض فلاش البالياج' },
    description: { en: 'Quick booking required! Our most popular balayage at 40% off.', ar: 'الحجز السريع مطلوب! البالياج الأكثر طلباً بخصم ٤٠٪.' },
    originalPrice: 450,
    discountedPrice: 270,
    discount: 40,
    expiresAt: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer13/600/400',
    salonId: '14',
    salonName: 'La Belle Coiffure',
  },
  {
    id: 'offer14',
    title: { en: 'Classic Lash Intro Offer', ar: 'عرض رموش كلاسيك تعريفي' },
    description: { en: 'Try classic lashes for the first time at this amazing price.', ar: 'جربي الرموش الكلاسيك لأول مرة بهذا السعر الرائع.' },
    originalPrice: 300,
    discountedPrice: 180,
    discount: 40,
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer14/600/400',
    salonId: '5',
    salonName: 'Sulaimaniyah Lash Bar',
  },
  {
    id: 'offer15',
    title: { en: 'Bridal Makeup + Hair', ar: 'مكياج عروس وشعر' },
    description: { en: 'Complete bridal look: hair + makeup for your special day.', ar: 'إطلالة العروس الكاملة: شعر ومكياج ليومك المميز.' },
    originalPrice: 950,
    discountedPrice: 699,
    discount: 26,
    expiresAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer15/600/400',
    salonId: '3',
    salonName: 'Malaz Bridal Studio',
  },
  {
    id: 'offer16',
    title: { en: 'Nail Art 3 Nails Free', ar: 'نقش ٣ أظافر مجاناً' },
    description: { en: 'Book gel nails and get 3 nail art designs for free.', ar: 'احجزي مناكير جل واحصلي على ٣ رسومات مجاناً.' },
    originalPrice: 180,
    discountedPrice: 120,
    discount: 33,
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer16/600/400',
    salonId: '16',
    salonName: 'Glow Up Beauty Bar',
  },
  {
    id: 'offer17',
    title: { en: 'Aromatherapy Massage Deal', ar: 'عرض مساج بالعطور' },
    description: { en: 'Relax and rejuvenate with our aromatherapy massage at a special price.', ar: 'استرخي وتجددي مع مساج العطور بسعر خاص.' },
    originalPrice: 400,
    discountedPrice: 280,
    discount: 30,
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer17/600/400',
    salonId: '17',
    salonName: 'Oasis Spa & Wellness',
  },
  {
    id: 'offer18',
    title: { en: 'Bridal Package Velvet', ar: 'باقة العروس فيلفيت' },
    description: { en: 'Premium bridal package with hair, makeup, nails and accessories.', ar: 'باقة عروس متميزة مع شعر ومكياج وأظافر.' },
    originalPrice: 2000,
    discountedPrice: 1400,
    discount: 30,
    expiresAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer18/600/400',
    salonId: '18',
    salonName: 'Velvet Touch Beauty',
  },
  {
    id: 'offer19',
    title: { en: 'Laser Session Bundle', ar: 'باقة جلسات الليزر' },
    description: { en: '5 laser hair removal sessions at a bundle price.', ar: '٥ جلسات إزالة شعر بالليزر بسعر الباقة.' },
    originalPrice: 3000,
    discountedPrice: 1999,
    discount: 33,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer19/600/400',
    salonId: '20',
    salonName: 'Radiance Skin Clinic',
  },
  {
    id: 'offer20',
    title: { en: 'Content Creator Package', ar: 'باقة صانع المحتوى' },
    description: { en: 'Perfect looks for your next photoshoot or video.', ar: 'إطلالة مثالية لجلسة التصوير القادمة.' },
    originalPrice: 500,
    discountedPrice: 350,
    discount: 30,
    expiresAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    image: 'https://picsum.photos/seed/offer20/600/400',
    salonId: '22',
    salonName: 'The Glam Room',
  },
];

export const reviews: Review[] = [
  { id: 'r1', customerName: 'Sara Al-Mansouri', customerAvatar: 'https://picsum.photos/seed/cust1/100/100', rating: 5, comment: { en: 'Absolutely amazing experience! The balayage turned out perfect and the staff was so professional.', ar: 'تجربة رائعة جداً! البالياج خرج مثالياً والموظفات محترفات جداً.' }, date: '2024-12-15', salonId: '1', service: 'Balayage' },
  { id: 'r2', customerName: 'Nora Al-Ghamdi', customerAvatar: 'https://picsum.photos/seed/cust2/100/100', rating: 5, comment: { en: 'Best nail salon in Riyadh! My gel nails lasted 4 weeks without chipping.', ar: 'أفضل صالون أظافر في الرياض! مناكيري الجل استمر ٤ أسابيع بدون تكسر.' }, date: '2024-12-10', salonId: '2', service: 'Gel Manicure' },
  { id: 'r3', customerName: 'Hessa Al-Rashid', customerAvatar: 'https://picsum.photos/seed/cust3/100/100', rating: 5, comment: { en: 'My bridal look was a dream come true. Everyone at the wedding complimented me.', ar: 'إطلالة عرسي كانت حلماً يتحقق. الجميع في الفرح مدحوني.' }, date: '2024-11-20', salonId: '3', service: 'Bridal Makeup' },
  { id: 'r4', customerName: 'Reem Al-Zahrani', customerAvatar: 'https://picsum.photos/seed/cust4/100/100', rating: 4, comment: { en: 'Great HydraFacial, my skin felt amazing after. Will definitely come back.', ar: 'هيدرا فيشل رائع، بشرتي شعرت بالنعومة بعده. سأعود بالتأكيد.' }, date: '2024-12-01', salonId: '4', service: 'HydraFacial' },
  { id: 'r5', customerName: 'Lina Al-Otaibi', customerAvatar: 'https://picsum.photos/seed/cust5/100/100', rating: 5, comment: { en: 'The volume lashes are stunning! So natural looking yet full and beautiful.', ar: 'رموش الفولوم مذهلة! طبيعية المظهر لكن كثيفة وجميلة.' }, date: '2024-12-08', salonId: '5', service: 'Volume Lash Set' },
  { id: 'r6', customerName: 'Mona Al-Dosari', customerAvatar: 'https://picsum.photos/seed/cust6/100/100', rating: 5, comment: { en: 'My microblading looks so natural! I wake up with perfect brows every day.', ar: 'مايكروبليدينجي يبدو طبيعياً جداً! أستيقظ بحواجب مثالية كل يوم.' }, date: '2024-11-28', salonId: '6', service: 'Microblading' },
  { id: 'r7', customerName: 'Dana Al-Harbi', customerAvatar: 'https://picsum.photos/seed/cust7/100/100', rating: 4, comment: { en: 'Very relaxing spa day. The hot stone massage was the highlight.', ar: 'يوم سبا مريح جداً. مساج الحجارة الساخنة كان الأفضل.' }, date: '2024-12-05', salonId: '7', service: 'Hot Stone Therapy' },
  { id: 'r8', customerName: 'Farah Al-Qahtani', customerAvatar: 'https://picsum.photos/seed/cust8/100/100', rating: 5, comment: { en: 'The Platinum experience is truly worth every riyal. Pure luxury.', ar: 'تجربة البلاتينيوم تستحق كل ريال. رفاهية حقيقية.' }, date: '2024-11-15', salonId: '12', service: 'VIP Package' },
  { id: 'r9', customerName: 'Nouf Al-Shehri', customerAvatar: 'https://picsum.photos/seed/cust9/100/100', rating: 5, comment: { en: 'La Belle is my go-to for hair! The colorists here are true artists.', ar: 'لا بيل هي وجهتي للشعر! المصففات هنا فنانات حقيقيات.' }, date: '2024-12-12', salonId: '14', service: 'Balayage' },
  { id: 'r10', customerName: 'Amal Al-Mutairi', customerAvatar: 'https://picsum.photos/seed/cust10/100/100', rating: 4, comment: { en: 'Crystal Nails never disappoints. My nails looked gorgeous for my wedding.', ar: 'كريستال نيلز لا تخذل أبداً. أظافري كانت رائعة في زفافي.' }, date: '2024-11-30', salonId: '10', service: 'Acrylic Full Set' },
  { id: 'r11', customerName: 'Khadija Al-Anazi', customerAvatar: 'https://picsum.photos/seed/cust11/100/100', rating: 5, comment: { en: 'The Glam Room is just perfect for content creators! The lighting and setup are amazing.', ar: 'ذا جلام روم مثالي لصانعي المحتوى! الإضاءة والديكور رائعان.' }, date: '2024-12-02', salonId: '22', service: 'Evening Makeup' },
  { id: 'r12', customerName: 'Rana Al-Salem', customerAvatar: 'https://picsum.photos/seed/cust12/100/100', rating: 5, comment: { en: 'Oasis Spa is my happy place. The aromatherapy massage melts all stress away.', ar: 'سبا أوازيس هو مكاني السعيد. مساج العطور يذيب كل التوتر.' }, date: '2024-12-07', salonId: '17', service: 'Aromatherapy Massage' },
  { id: 'r13', customerName: 'Wafa Al-Khaldi', customerAvatar: 'https://picsum.photos/seed/cust13/100/100', rating: 4, comment: { en: 'Great nail art at Crystal Nails! Very detailed and long-lasting.', ar: 'نقش أظافر رائع في كريستال نيلز! دقيق جداً وطويل الأمد.' }, date: '2024-11-25', salonId: '10', service: 'Nail Art' },
  { id: 'r14', customerName: 'Sana Al-Yami', customerAvatar: 'https://picsum.photos/seed/cust14/100/100', rating: 5, comment: { en: 'Bloom Lashes gave me the most beautiful hybrid set. So wispy and natural!', ar: 'بلوم لاشيز أعطتني أجمل مجموعة هايبرد. ريشية وطبيعية جداً!' }, date: '2024-12-09', salonId: '19', service: 'Hybrid Lash Set' },
  { id: 'r15', customerName: 'Ghada Al-Rashidi', customerAvatar: 'https://picsum.photos/seed/cust15/100/100', rating: 5, comment: { en: 'Crown Beauty Palace is truly royal! Every detail is perfect.', ar: 'قصر كراون للجمال ملكي حقاً! كل تفصيل مثالي.' }, date: '2024-11-10', salonId: '29', service: 'Full Package' },
  { id: 'r16', customerName: 'Hind Al-Fawzan', customerAvatar: 'https://picsum.photos/seed/cust16/100/100', rating: 4, comment: { en: 'Shimmer & Shine is great value for money. Good quality at affordable prices.', ar: 'شيمر وشاين قيمة ممتازة مقابل المال. جودة جيدة بأسعار معقولة.' }, date: '2024-12-03', salonId: '13', service: 'Haircut & Style' },
  { id: 'r17', customerName: 'Amira Al-Thubaiti', customerAvatar: 'https://picsum.photos/seed/cust17/100/100', rating: 5, comment: { en: 'Velvet Touch Beauty made me look absolutely stunning for my sister\'s wedding.', ar: 'فيلفيت تاتش بيوتي جعلتني أبدو رائعة في زواج أختي.' }, date: '2024-11-18', salonId: '18', service: 'Bridal Makeup' },
  { id: 'r18', customerName: 'Dalal Al-Juhani', customerAvatar: 'https://picsum.photos/seed/cust18/100/100', rating: 5, comment: { en: 'The Japanese nail techniques at Sakura are unlike anything I\'ve tried before.', ar: 'تقنيات الأظافر اليابانية في ساكورا لا مثيل لها.' }, date: '2024-12-11', salonId: '28', service: 'Gel Manicure' },
  { id: 'r19', customerName: 'Rawan Al-Ghamdi', customerAvatar: 'https://picsum.photos/seed/cust19/100/100', rating: 4, comment: { en: 'Radiance Skin Clinic is professional and clean. The laser sessions are effective.', ar: 'عيادة راديانس للبشرة احترافية ونظيفة. جلسات الليزر فعالة.' }, date: '2024-11-22', salonId: '20', service: 'Laser Hair Removal' },
  { id: 'r20', customerName: 'Mariam Al-Saaidi', customerAvatar: 'https://picsum.photos/seed/cust20/100/100', rating: 5, comment: { en: 'Lumière is simply the best! I drive from the other side of Riyadh just for them.', ar: 'لوميير ببساطة الأفضل! أقود من الجانب الآخر من الرياض خصيصاً لهم.' }, date: '2024-12-14', salonId: '1', service: 'Keratin Treatment' },
  { id: 'r21', customerName: 'Latifa Al-Kabeer', customerAvatar: 'https://picsum.photos/seed/cust21/100/100', rating: 5, comment: { en: 'Gold Rose Beauty never misses. Perfect color every single time.', ar: 'جولد روز بيوتي لا تفشل أبداً. لون مثالي في كل مرة.' }, date: '2024-12-06', salonId: '8', service: 'Hair Color Full' },
  { id: 'r22', customerName: 'Hanan Al-Shahrani', customerAvatar: 'https://picsum.photos/seed/cust22/100/100', rating: 4, comment: { en: 'Yasmin Hair has great stylists and the atmosphere is very relaxing.', ar: 'ياسمين هير لديها مصففات رائعات والجو مريح جداً.' }, date: '2024-11-29', salonId: '9', service: 'Blowout' },
  { id: 'r23', customerName: 'Asma Al-Jabri', customerAvatar: 'https://picsum.photos/seed/cust23/100/100', rating: 5, comment: { en: 'Aura Spa is a hidden gem. The signature massage is beyond amazing.', ar: 'أورا سبا جوهرة خفية. المساج المميز أبعد من الرائع.' }, date: '2024-12-04', salonId: '23', service: 'Signature Massage' },
  { id: 'r24', customerName: 'Shahad Al-Fulaij', customerAvatar: 'https://picsum.photos/seed/cust24/100/100', rating: 5, comment: { en: 'Chic Nails is my favorite! The Korean nail techniques are so delicate and beautiful.', ar: 'شيك نيلز هي المفضلة لدي! تقنيات الأظافر الكورية دقيقة وجميلة.' }, date: '2024-12-10', salonId: '24', service: 'Gel Manicure' },
  { id: 'r25', customerName: 'Taif Al-Kubaisi', customerAvatar: 'https://picsum.photos/seed/cust25/100/100', rating: 4, comment: { en: 'Bliss Beauty Studio uses organic products which I love! Great for sensitive skin.', ar: 'بليس بيوتي ستوديو يستخدم منتجات عضوية أحبها! رائع للبشرة الحساسة.' }, date: '2024-11-26', salonId: '25', service: 'Haircut & Style' },
  { id: 'r26', customerName: 'Maha Al-Barrak', customerAvatar: 'https://picsum.photos/seed/cust26/100/100', rating: 5, comment: { en: 'Diamond Lash does the most stunning mega volume sets! My lashes are everything.', ar: 'دايموند لاش تعمل أجمل مجموعات الميجا فولوم! رموشي كل شيء.' }, date: '2024-12-08', salonId: '26', service: 'Mega Volume Lashes' },
  { id: 'r27', customerName: 'Nadia Al-Muzaini', customerAvatar: 'https://picsum.photos/seed/cust27/100/100', rating: 5, comment: { en: 'Maison de Beauté is pure elegance. The staff makes you feel like royalty.', ar: 'ميزون دو بوتيه رقي خالص. الموظفات يجعلنك تشعرين كملكة.' }, date: '2024-11-20', salonId: '27', service: 'Full Package' },
  { id: 'r28', customerName: 'Basma Al-Shammari', customerAvatar: 'https://picsum.photos/seed/cust28/100/100', rating: 4, comment: { en: 'Studio 99 is so creative! They did a bold color on my hair that I love.', ar: 'ستوديو ٩٩ إبداعي جداً! عملوا لون جريء على شعري أعشقه.' }, date: '2024-12-01', salonId: '30', service: 'Hair Color Full' },
  { id: 'r29', customerName: 'Reema Al-Alawi', customerAvatar: 'https://picsum.photos/seed/cust29/100/100', rating: 5, comment: { en: 'Worood Eyebrow Studio transformed my brows completely. So happy with my lamination.', ar: 'ورود ستوديو الحواجب غيّر حواجبي تماماً. سعيدة جداً باللاميناشن.' }, date: '2024-12-13', salonId: '6', service: 'Eyebrow Lamination' },
  { id: 'r30', customerName: 'Hoor Al-Khalaf', customerAvatar: 'https://picsum.photos/seed/cust30/100/100', rating: 5, comment: { en: 'Pearl Beauty Center has it all! Great value and quality across every service.', ar: 'مركز بيرل للجمال يملك كل شيء! قيمة وجودة ممتازة في كل خدمة.' }, date: '2024-11-15', salonId: '21', service: 'Full Package' },
];

export const packages: Package[] = [
  {
    id: 'pkg1',
    name: { en: 'Glow Goddess Package', ar: 'باقة إلهة الإشراق' },
    description: { en: 'The complete beauty transformation for your special occasion.', ar: 'التحول الجمالي الكامل لمناسبتك المميزة.' },
    services: ['Balayage', 'Facial', 'Gel Manicure & Pedicure', 'Makeup'],
    originalPrice: 1600,
    price: 999,
    image: 'https://picsum.photos/seed/pkg1/600/400',
    duration: 360,
  },
  {
    id: 'pkg2',
    name: { en: 'Bridal Bliss Package', ar: 'باقة سعادة العروس' },
    description: { en: 'Everything a bride needs to look her absolute best on her big day.', ar: 'كل ما تحتاجه العروس لتبدو في أحسن حال في يومها المميز.' },
    services: ['Bridal Makeup', 'Hair Styling', 'Acrylic Nails', 'Lash Extensions', 'Eyebrow Design'],
    originalPrice: 2800,
    price: 1899,
    image: 'https://picsum.photos/seed/pkg2/600/400',
    duration: 480,
  },
  {
    id: 'pkg3',
    name: { en: 'Self-Care Sunday', ar: 'أحد العناية بالنفس' },
    description: { en: 'A relaxing day dedicated entirely to your wellbeing and beauty.', ar: 'يوم مريح مخصص تماماً لصحتك وجمالك.' },
    services: ['Swedish Massage', 'HydraFacial', 'Manicure', 'Blowout'],
    originalPrice: 1100,
    price: 749,
    image: 'https://picsum.photos/seed/pkg3/600/400',
    duration: 300,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'blog1',
    title: { en: 'Top 10 Hair Color Trends in Saudi Arabia 2025', ar: 'أفضل ١٠ اتجاهات لصبغ الشعر في السعودية ٢٠٢٥' },
    excerpt: { en: 'Discover the hottest hair color trends that are taking Riyadh\'s salons by storm this year.', ar: 'اكتشفي أحدث اتجاهات صبغ الشعر التي تجتاح صالونات الرياض هذا العام.' },
    image: 'https://picsum.photos/seed/blog1/800/500',
    category: 'Hair',
    date: '2024-12-10',
    readTime: 5,
  },
  {
    id: 'blog2',
    title: { en: 'The Ultimate Skincare Routine for the GCC Climate', ar: 'روتين العناية بالبشرة المثالي لمناخ دول الخليج' },
    excerpt: { en: 'Expert tips on how to keep your skin glowing despite the heat and humidity.', ar: 'نصائح خبراء للحفاظ على بشرة مشرقة رغم الحرارة والرطوبة.' },
    image: 'https://picsum.photos/seed/blog2/800/500',
    category: 'Skincare',
    date: '2024-12-05',
    readTime: 7,
  },
  {
    id: 'blog3',
    title: { en: 'How to Choose the Perfect Bridal Makeup Artist', ar: 'كيف تختارين فنانة المكياج المثالية للعرائس' },
    excerpt: { en: 'A comprehensive guide to finding and booking the right makeup artist for your wedding day.', ar: 'دليل شامل للعثور على فنانة المكياج المناسبة وحجزها ليوم زفافك.' },
    image: 'https://picsum.photos/seed/blog3/800/500',
    category: 'Bridal',
    date: '2024-11-28',
    readTime: 6,
  },
];

export const sampleBookings = [
  {
    id: 'bk1',
    salonId: '1',
    salonName: 'Lumière Beauty Lounge',
    service: 'Balayage',
    staff: 'Sara Al-Ahmad',
    date: '2025-01-15',
    time: '10:00 AM',
    status: 'upcoming',
    price: 450,
  },
  {
    id: 'bk2',
    salonId: '2',
    salonName: 'Nakheel Nail Studio',
    service: 'Gel Manicure',
    staff: 'Nour Al-Rashid',
    date: '2024-12-20',
    time: '2:00 PM',
    status: 'completed',
    price: 120,
  },
  {
    id: 'bk3',
    salonId: '7',
    salonName: 'Serenity Spa & Massage',
    service: 'Hot Stone Therapy',
    staff: 'Reem Al-Dosari',
    date: '2024-11-30',
    time: '11:00 AM',
    status: 'completed',
    price: 500,
  },
  {
    id: 'bk4',
    salonId: '5',
    salonName: 'Sulaimaniyah Lash Bar',
    service: 'Volume Lash Set',
    staff: 'Maya Al-Zahrani',
    date: '2024-11-10',
    time: '3:00 PM',
    status: 'cancelled',
    price: 450,
  },
];

export const getSalonById = (id: string): Salon | undefined => {
  return salons.find(salon => salon.id === id);
};

export const getOfferById = (id: string): Offer | undefined => {
  return offers.find(offer => offer.id === id);
};

export const getSalonsByCategory = (category: string): Salon[] => {
  return salons.filter(salon => salon.category === category);
};

export const getFeaturedSalons = (): Salon[] => {
  return salons.filter(s => s.rating >= 4.7).slice(0, 6);
};

export const getLuxurySalons = (): Salon[] => {
  return salons.filter(s => s.isLuxury).slice(0, 6);
};
